language: java
dist: xenial

addons:
  apt:
    packages:
      - libibverbs-dev
      - libibmad-dev
      - libibumad-dev
      - libibnetdisc-dev
      - libopensm-dev

stages:
  - name: build
  - name: snapshot
    if: branch = development AND type = push
  - name: release
    if: branch = master AND type = push

jobs:
  include:
    - stage: build
      script: ./gradlew jar
    - stage: snapshot
      script: ./gradlew artifactoryPublish -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}
    - stage: release
      script: ./gradlew bintrayUpload -Drelease=true -PbuildVariant=release -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}

before_deploy:
  - export RELEASE_JAR_FILE=$(ls build/libs/*.jar)

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  file: ${RELEASE_JAR_FILE}
  skip_cleanup: true
  overwrite: true
  on:
    repo: hhu-bsinfo/jibperf-lib
    branch: master
    tags: true