os: linux
dist: xenial
language: java

addons:
  apt:
    packages:
      - libibverbs-dev
      - libibmad-dev
      - libibumad-dev
      - libibnetdisc-dev
      - libopensm-dev

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        - ./gradlew cmakeBuild build
    - stage: release
      script:
        - ./gradlew clean
        - ./gradlew publish -Dgpr.user=${GPR_USER} -Dgpr.token=${GPR_TOKEN} -Drelease=true
        - ./gradlew sourcesJar javadocJar -Drelease=true
        - export PUBLISH=true

deploy:
  provider: releases
  token: ${ACCESS_TOKEN}
  file: build/libs/jdetector-${TRAVIS_TAG}.jar
  skip_cleanup: true
  overwrite: true
  on:
    repo: hhu-bsinfo/jdetector
    branch: master
    tags: true
    condition: ${PUBLISH} = true
